export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

export const GET_MEMES_REQUEST = 'GET_MEMES_REQUEST';
export const GET_MEMES_SUCCESS = 'GET_MEMES_SUCCESS';
export const GET_MEMES_FAILED = 'GET_MEMES_FAILED';

export const GET_SINGLE_MEME_REQUEST = 'GET_SINGLE_MEME_REQUEST';
export const GET_SINGLE_MEME_SUCCESS = 'GET_SINGLE_MEME_SUCCESS';
export const GET_SINGLE_MEME_FAILED = 'GET_SINGLE_MEME_FAILED';

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILED = 'GET_COMMENTS_FAILED';
export const COMMENT_SUCCESS = 'COMMENTS_SUCCESS';
export const COMMENT_FAILED = 'COMMENT_FAILED';

export const CREATE_MEME_SUCCESS = 'CREATE_MEME_SUCCESS';
export const CREATE_MEME_FAILED = 'CREATE_MEME_FAILED';

export const DELETE_MEME_REQUEST = 'DELETE_MEME_REQUEST';
export const DELETE_MEME_SUCCESS = 'DELETE_MEME_SUCCESS';
export const DELETE_MEME_FAILED = 'DELETE_MEME_FAILED';
export const DELETE_MEME_RESET = 'DELETE_MEME_RESET';

export const MEME_LIKED_SUCCESS = 'MEME_LIKED_SUCCESS';
export const MEME_LIKED_FAILED = 'MEME_LIKED_FAILED';

export const GET_USER_MEMES_REQUEST = 'GET_USER_MEMES_REQUEST';
export const GET_USER_MEMES_SUCCESS = 'GET_USER_MEMES_SUCCESS';
export const GET_USER_MEMES_FAILED = 'GET_USER_MEMES_FAILED';

export const PASSWORD_RESET_LINK_REQUEST = 'PASSWORD_RESET_LINK_REQUEST';
export const PASSWORD_RESET_LINK_SUCCESS = 'PASSWORD_RESET_LINK_SUCCESS';
export const PASSWORD_RESET_LINK_FAILED = 'PASSWORD_RESET_LINK_FAILED';
export const PASSWORD_RESET_LINK_RESET = 'PASSWORD_RESET_LINK_RESET';

export const RESET_PASSEORD_REQUEST = 'RESET_PASSEORD_REQUEST';
export const RESET_PASSEORD_SUCCESS = 'RESET_PASSEORD_SUCCESS';
export const RESET_PASSEORD_FAILED = 'RESET_PASSEORD_FAILED';
export const RESET_PASSEORD_RESET = 'RESET_PASSEORD_RESET';
